services:
  # Django API container
  django:
    build:
      context: ./api
    volumes:
      - ./api/staticfiles:/app/staticfiles  # Mount static files directory
      - ./api/logs:/app/logs  # Mount logs directory (persistent logs)
    command: ["gunicorn", "wsgi:application", "-b", "0.0.0.0:8000"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=blab_db
      - DB_USER=admin
      - DB_PASSWORD=Letacla01*
    networks:
      - backend

  # Database container (PostgreSQL example)
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blab_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Letacla01*
    networks:
      - backend

  # Vue.js frontend container
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Change the port to 80 for Nginx
      - "443:443"  # Change the port to 443 for Nginx
    depends_on:
      - django
    volumes:
      - ./frontend/nginx/cert.crt:/etc/ssl/certs/cert.crt
      - ./frontend/nginx/cert.key:/etc/ssl/private/cert.key
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./api/staticfiles:/usr/share/nginx/html/static  # Mount static files directory for Nginx
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
