# Generated by Django 5.0.4 on 2026-09-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mngt_IP', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('console', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255)),
                ('hardware_revision', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.switch')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_switch', models.CharField(max_length=255)),
                ('backbone', models.CharField(max_length=255)),
                ('port_backbone', models.CharField(max_length=255)),
                ('svlan', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, choices=[('UP', 'Up'), ('DOWN', 'Down')], default='DOWN', max_length=10, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.switch')),
            ],
        ),
        migrations.CreateModel(
            name='TopologyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_topologies', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_topologies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
