# Generated by Django 5.0.4 on 2024-04-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="port_backbone",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="port",
            name="port_switch",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="port",
            name="svlan",
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
