# Generated by Django 5.0.4 on 2026-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='teardown_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='teardown_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='teardown_svlan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
