# Generated by Django 5.0.4 on 2024-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_reservation_user_alter_port_port_backbone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="svlan",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
