# Generated by Django 5.0.4 on 2026-10-07 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_port_teardown'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(help_text='Switch port, as in show interfaces (e.g. 1/1/5)', max_length=32)),
                ('note', models.CharField(blank=True, help_text='What it is cabled to, and why it stays', max_length=255)),
                ('switch', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_cables', to='api.switch')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inspection', 'Inspection')], max_length=32)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(null=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('switch', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.switch')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['switch', '-at'], name='api_switche_switch__57d137_idx')],
            },
        ),
    ]
