# Generated by Django 5.0.4 on 2026-10-08 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='out_of_service_reason',
            field=models.CharField(blank=True, help_text='Set to take the Switch out of reservation; empty it to put it back', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='out_of_service_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switchevent',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PendingCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('next_inspection_at', models.DateTimeField(blank=True, null=True)),
                ('give_up_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='pending_cleanup', to='api.switch')),
            ],
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantines', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quarantines', to='api.switch')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
    ]
