# Generated by Django 5.0.4 on 2024-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_port_svlan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="switch",
            old_name="Model",
            new_name="model",
        ),
    ]
