# Generated by Django 5.0.4 on 2026-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_switchevent_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='admin_exception',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='renewals',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
