# Generated by Django 5.0.4 on 2026-10-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cap_existing_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # A new table: main's code never reads or writes it (docs/adr/0002). Its unique constraint
    # comes with the table, so it can't reject rows main writes.
    operations = [
        migrations.CreateModel(
            name='SwitchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('password', models.CharField(max_length=64)),
                ('created', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('tried_at', models.DateTimeField(blank=True, null=True)),
                ('switch', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.switch')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('switch', 'user'), name='one_switch_account_per_user')],
            },
        ),
    ]
