# Generated by Django 5.0.4 on 2026-10-09 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    # The constraint is on the new Sweep table, which main's code knows nothing of and never writes
    shared_db_safe = True

    dependencies = [
        ('api', '0008_switch_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('under_way', models.BooleanField(default=True, null=True)),
                ('swept', models.JSONField(blank=True, default=list)),
                ('skipped', models.JSONField(blank=True, default=list)),
                ('cleanups_asked', models.JSONField(blank=True, default=list)),
                ('quarantines_seen', models.JSONField(blank=True, default=list)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sweep',
            constraint=models.UniqueConstraint(fields=('under_way',), name='one_sweep_under_way'),
        ),
    ]
