# Generated by Django 5.0.4 on 2026-10-09 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # A new table only, its unique constraint created with it: main's code never touches it (ADR 0002)

    dependencies = [
        ('api', '0009_sweep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.switch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'switch'), name='one_position_per_switch')],
            },
        ),
    ]
