# Generated by Django 5.0.4 on 2026-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_topology_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='ghost_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='ghost_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='ghost_svlan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
